ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    application {
        modules = [ ApplicationKt.module ]
    }
}

// 指定AI模型
model = "DeepSeek"
// 代理需要使用浏览器，如果指定了`browser_path`则使用`browser_path`指定的浏览器。否则依次尝试使用Edge和Chrome
// 如果无法找到浏览器，则自动下载。默认禁止下载
auto_download_browser = false
// 如果找不到浏览器且禁止自动下载，则需要明确指定浏览器的路径
// browser_path = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
// 是否保存代理浏览器的session数据，如cookies 和 local storage
persistent_context = true
//指定代理浏览器session数据保存的位置。默认保存在 ~/.AiFree/context_data
// context_data_dir =
// 代理浏览器是否以headless模式执行
headless = false
